/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "eu-central-1",
  "aws_cognito_identity_pool_id": "XXXXX",
  "aws_cognito_region": "eu-central-1",
  "aws_user_pools_id": "XXXXX",
  "aws_user_pools_web_client_id": "XXXXX",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_appsync_graphqlEndpoint": "XXXXX",
  "aws_appsync_region": "eu-central-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "XXXXX",
  "aws_content_delivery_bucket": "XXXXX",
  "aws_content_delivery_bucket_region": "eu-central-1",
  "aws_content_delivery_url": "XXXXX",
  "aws_cognito_login_mechanisms": [
      "EMAIL"
  ]
};


export default awsmobile;
